LogicUniversityWebApp/LogicUniversityApp/Models/Inventory.cs
namespace LogicUniversityApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Inventory")]
    public partial class Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory()
        {
            AdjustmentVouchers = new HashSet<AdjustmentVoucher>();
            Pricings = new HashSet<Pricing>();
            PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
            RequestDetails = new HashSet<RequestDetail>();
            StockCards = new HashSet<StockCard>();
        }

        [Key]
        [StringLength(10)]
        [DisplayName("Item Number")]
        public string itemNo { get; set; }

        [Required]
        [StringLength(10)]
        [DisplayName("Category")]
        public string category { get; set; }

        [Required]
        [DisplayName("Item")]
        public string description { get; set; }

        [DisplayName("Balance")]
        public int? balance { get; set; }

        [DisplayName("Reorder Level")]
        public int reorderLevel { get; set; }

        [DisplayName("Reorder Qty")]
        public int reorderQuantity { get; set; }

        [Required]
        [StringLength(20)]
        [DisplayName("Unit")]
        public string unitMeasure { get; set; }

        [DisplayName("Price")]
        public decimal stdPrice { get; set; }

        [Required]
        [StringLength(25)]
        [DisplayName("Supplier 1")]
        public string supplierId1 { get; set; }

        [Required]
        [StringLength(25)]
        [DisplayName("Supplier 2")]
        public string supplierId2 { get; set; }

        [Required]
        [StringLength(25)]
        [DisplayName("Supplier 3")]
        public string supplierId3 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdjustmentVoucher> AdjustmentVouchers { get; set; }

        public virtual Category Category1 { get; set; }

        public virtual Supplier Supplier { get; set; }

        public virtual Supplier Supplier1 { get; set; }

        public virtual Supplier Supplier2 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pricing> Pricings { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestDetail> RequestDetails { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockCard> StockCards { get; set; }
    }
}

LogicUniversityWebApp/LogicUniversityApp/Controllers/InventoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LogicUniversityApp.Models;
using LogicUniversityApp.ViewModel;

namespace LogicUniversityApp.Controllers
{
    public class InventoriesController : Controller
    {
        // GET: Inventories
        public ActionResult Index(string category, string searchString)
        {
            ViewBag.category = AdjustmentVoucherDAO.GetCategorySelectList();

            List<InventoryViewModel> inventories = AdjustmentVoucherDAO.GetInventoryViewModels();

            if (!String.IsNullOrEmpty(searchString))
            {
                inventories = inventories.Where(s => s.description.ToUpper().Contains(searchString.ToUpper())).ToList();
            }

            if (!string.IsNullOrEmpty(category))
            {
                inventories = inventories.Where(x => x.category == category).ToList();
            }
            return View(inventories.ToList());
        }

        // GET: Inventories/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InventoryViewModel inventory = InventoryDAO.GetInventoryByItemNo(id);
            return View(inventory);
        }

        // GET: Inventories/Create
        public ActionResult Create()
        {
            List<SelectListItem> listItem = new List<SelectListItem>
            {
                new SelectListItem{Text="Dozen",Value="Dozen"},
                new SelectListItem{Text="Box",Value="Box"},
                new SelectListItem{Text="Each",Value="Each"},
                new SelectListItem{Text="Set",Value="Set"},
                new SelectListItem{Text="Packet",Value="Packet"}
            };

            ViewBag.unitMeasure = new SelectList(listItem, "Value", "Text");
            ViewBag.category = AdjustmentVoucherDAO.GetCategorySelectList();
            ViewBag.supplierId1 = AdjustmentVoucherDAO.GetSupplierSelectList();
            ViewBag.supplierId2 = AdjustmentVoucherDAO.GetSupplierSelectList();
            ViewBag.supplierId3 = AdjustmentVoucherDAO.GetSupplierSelectList();
            return View();
        }

        // POST: Inventories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(InventoryViewModel inventoryViewModel)
        {
            if (!ModelState.IsValid)
            {
                List<SelectListItem> listItem = new List<SelectListItem>
                {
                    new SelectListItem{Text="Dozen",Value="Dozen"},
                    new SelectListItem{Text="Box",Value="Box"},
                    new SelectListItem{Text="Each",Value="Each"},
                    new SelectListItem{Text="Set",Value="Set"},
                    new SelectListItem{Text="Packet",Value="Packet"}
                };

                ViewBag.unitMeasure = new SelectList(listItem, "Value", "Text");
                ViewBag.category = AdjustmentVoucherDAO.GetCategorySelectList();
                ViewBag.supplierId1 = AdjustmentVoucherDAO.GetSupplierSelectList();
                ViewBag.supplierId2 = AdjustmentVoucherDAO.GetSupplierSelectList();
                ViewBag.supplierId3 = AdjustmentVoucherDAO.GetSupplierSelectList();

                return View(inventoryViewModel);
            }

            bool result = AdjustmentVoucherDAO.CreateInventories(inventoryViewModel);
            if (!result)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
            return RedirectToAction("Index");
        }

        // GET: Inventories/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            InventoryViewModel inventoryViewModel = InventoryDAO.GetInventoryByItemNo(id);

            if (inventoryViewModel == null)
            {
                return View("~/Views/Shared/Error.cshtml");
            };

            // drop down list 
            List<String> listItem = new List<string>();
            listItem.Add("Dozen");
            listItem.Add("Box");
            listItem.Add("Each");
            listItem.Add("Set");
            listItem.Add("Packet");
            ViewBag.unitMeasure = new SelectList(listItem, inventoryViewModel.unitMeasure);

            // drop down list 
            var categories = InventoryDAO.getAllCategoryId();
            ViewBag.category = new SelectList(categories, inventoryViewModel.category);

            // push to view
            return View(inventoryViewModel);
        }

        // POST: Inventories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(InventoryViewModel inventoryViewModel)
        {
            if (!ModelState.IsValidField(nameof(InventoryViewModel.itemNo))
                || !ModelState.IsValidField(nameof(InventoryViewModel.category))
                || !ModelState.IsValidField(nameof(InventoryViewModel.description))
                || !ModelState.IsValidField(nameof(InventoryViewModel.unitMeasure))
                || !ModelState.IsValidField(nameof(InventoryViewModel.reorderQuantity))
                || !ModelState.IsValidField(nameof(InventoryViewModel.reorderLevel))
                || !ModelState.IsValidField(nameof(InventoryViewModel.stdPrice))
                || !ModelState.IsValidField(nameof(InventoryViewModel.balance))
                )
            {
                // drop down list 
                List<String> listItem = new List<string>();
                listItem.Add("Dozen");
                listItem.Add("Box");
                listItem.Add("Each");
                listItem.Add("Set");
                listItem.Add("Packet");
                ViewBag.unitMeasure = new SelectList(listItem, inventoryViewModel.unitMeasure);

                // drop down list 
                var categories = InventoryDAO.getAllCategoryId();
                ViewBag.category = new SelectList(categories, inventoryViewModel.category);

                return View(inventoryViewModel);
            }

            // biz logic here...
            bool bRes = AdjustmentVoucherDAO.EditInventories(inventoryViewModel);
            if (bRes)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }

        // GET: Inventories/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InventoryViewModel inventoryViewModel = InventoryDAO.GetInventoryByItemNo(id);
            if (inventoryViewModel == null)
            {
                return HttpNotFound();
            }
            return View(inventoryViewModel);
        }

        // POST: Inventories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            InventoryViewModel inventoryViewModel = InventoryDAO.GetInventoryByItemNo(id);
            bool result = AdjustmentVoucherDAO.DeleteInventories(inventoryViewModel);
            if (!result)
            {
                return View("~/Views/Shared/Error.cshtml");
            }

            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        DbFactory.Instance.context.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

LogicUniversityWebApp/LogicUniversityApp/Views/Inventories/Create.cshtml
@model LogicUniversityApp.ViewModel.InventoryViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Inventory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.itemNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.itemNo, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.EditorFor(model => model.itemNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.itemNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.category, "category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("category", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.balance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.balance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.balance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.reorderLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.reorderLevel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.reorderLevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.reorderQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.reorderQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.reorderQuantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.unitMeasure, "unitMeasure", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("unitMeasure", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.unitMeasure, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.stdPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.stdPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.stdPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.supplierId1, "supplierId1", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("supplierId1", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.supplierId1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.supplierId2, "supplierId2", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("supplierId2", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.supplierId2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.supplierId3, "supplierId3", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("supplierId3", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.supplierId3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

LogicUniversityWebApp/LogicUniversityApp/Views/Inventories/Delete.cshtml
@model LogicUniversityApp.ViewModel.InventoryViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Inventory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.balance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.balance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.reorderLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.reorderLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.reorderQuantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.reorderQuantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.unitMeasure)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.unitMeasure)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.stdPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.stdPrice)
        </dd>



        <dt>
            @Html.DisplayNameFor(model => model.supplierId1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.supplierId1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.supplierId2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.supplierId2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.supplierId3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.supplierId3)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LogicUniversityWebApp/LogicUniversityApp/Views/Inventories/Details.cshtml
@model LogicUniversityApp.ViewModel.InventoryViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>InventoryViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.itemNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.itemNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.balance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.balance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.reorderLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.reorderLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.reorderQuantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.reorderQuantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.unitMeasure)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.unitMeasure)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.stdPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.stdPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.supplierId1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.supplierId1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.supplierId2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.supplierId2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.supplierId3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.supplierId3)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

LogicUniversityWebApp/LogicUniversityApp/Views/Inventories/Edit.cshtml
@model LogicUniversityApp.ViewModel.InventoryViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>INVENTORY</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(x => x.itemNo)

        <div class="form-group">
            @Html.LabelFor(model => model.category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("category", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.balance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.balance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.balance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.reorderLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.reorderLevel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.reorderLevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.reorderQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.reorderQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.reorderQuantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.unitMeasure, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("unitMeasure", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.unitMeasure, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.stdPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.stdPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.stdPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

LogicUniversityWebApp/LogicUniversityApp/Views/Inventories/Index.cshtml
@model IEnumerable<LogicUniversityApp.ViewModel.InventoryViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Inventories", FormMethod.Get))
{
    <p>
        Category: @Html.DropDownList("category", "ALL")
        Title: @Html.TextBox("SearchString")

        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.itemNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.reorderLevel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.reorderQuantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.unitMeasure)
        </th>


        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.itemNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.reorderLevel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.reorderQuantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.unitMeasure)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.itemNo }) |
                @Html.ActionLink("Details", "Details", new { id = item.itemNo }) 
                @*|
                @Html.ActionLink("Delete", "Delete", new { id = item.itemNo })*@
            </td>
        </tr>
    }

</table>