LogicUniversityWebApp/LogicUniversityApp/Controllers/RetrievalController.cs
using LogicUniversityApp.Models;
using LogicUniversityApp.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LogicUniversityApp.Controllers
{
    public class RetrievalController : Controller
    {
        // GET: Retrieval
        [HttpGet]
        public ActionResult Index(string DueDate)
        {
            List<RetrievalViewModel> Res = new List<RetrievalViewModel>();

            if (DueDate != null)
            {
                if (DateTime.TryParse(DueDate, out DateTime myDate))
                {
                    ViewBag.myDate = DueDate;
                    Res = RequestDAO.ViewRetrievalGoods(myDate);
                }
            }
            else
            {
                // the default date is today
                DateTime myDate = DateTime.Now.Date;
                ViewBag.myDate = myDate.ToString("yyyy/MM/dd");
                Res = RequestDAO.ViewRetrievalGoods(myDate);
            }
            return View(Res);
        }

        public ActionResult Edit(string itemNo, DateTime DueDate)
        {
            var myModel = RequestDAO.ViewRetrievalGood(itemNo, DueDate);

            return View(myModel);
        }

        // itemNo*, DueDate*, quantityRetrieval, quantityInstoreDamaged, quantityInstoreMissing
        [HttpPost]
        public ActionResult Edit(RetrievalViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            bool bRes = RequestDAO.AllocateGoods(
                model.itemNo,
                model.DueDate,
                model.quantityRetrieval,
                model.quantityInstoreDamaged,
                model.quantityInstoreMissing);

            if (bRes)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }
    }


}

LogicUniversityWebApp/LogicUniversityApp/Views/Retrieval/Edit.cshtml
@model LogicUniversityApp.ViewModel.RetrievalViewModel

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <br/>

    <table class="table table-striped table-hover">
        <tr>
            <th class="text-center text-info">@Html.DisplayNameFor(model => model.DueDate)</th>
            <th class="text-center text-info">@Html.DisplayNameFor(model => model.itemNo)</th>
            <th class="text-center text-info">@Html.DisplayNameFor(model => model.description)</th>
            <th class="text-center text-info">@Html.DisplayNameFor(model => model.categoryId)</th>
            <th class="text-center text-info">@Html.DisplayNameFor(model => model.location)</th>
            <th class="text-center text-info">@Html.DisplayNameFor(model => model.balance)</th>
            <th class="text-center text-info">@Html.DisplayNameFor(model => model.unitMeasure)</th>
        </tr>
        <tr>
            <td align="center">
                @Html.HiddenFor(model => model.DueDate)
                @Html.DisplayFor(model => model.DueDate)
            </td>
            <td align="center">
                @Html.HiddenFor(model => model.itemNo)
                @Html.DisplayFor(model => model.itemNo)
            </td>
            <td align="center">
                @Html.HiddenFor(model => model.description)
                @Html.DisplayFor(model => model.description)
            </td>
            <td align="center">
                @Html.HiddenFor(model => model.categoryId)
                @Html.DisplayFor(model => model.categoryId)
            </td>
            <td align="center">
                @Html.HiddenFor(model => model.location)
                @Html.DisplayFor(model => model.location)
            </td>
            <td align="center">
                @Html.HiddenFor(model => model.balance)
                @Html.DisplayFor(model => model.balance)
            </td>
            <td align="center">
                @Html.HiddenFor(model => model.unitMeasure)
                @Html.DisplayFor(model => model.unitMeasure)
            </td>
        </tr>
    </table>

    <div class="form-horizontal">        
        <div class="form-group">
            @Html.LabelFor(model => model.quantityTotalNeed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.quantityTotalNeed)
                @Html.DisplayFor(model => model.quantityTotalNeed)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantityRetrieval, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="control-label col-md-2">
                @Html.EditorFor(model => model.quantityRetrieval, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantityRetrieval, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantityInstoreDamaged, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="control-label col-md-2">
                @Html.EditorFor(model => model.quantityInstoreDamaged, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantityInstoreDamaged, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantityInstoreMissing, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="control-label col-md-2">
                @Html.EditorFor(model => model.quantityInstoreMissing, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantityInstoreMissing, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LogicUniversityWebApp/LogicUniversityApp/Views/Retrieval/Index.cshtml
@model IEnumerable<LogicUniversityApp.ViewModel.RetrievalViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/jquery-ui.min.js"></script>

@section scripts{

    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

    <script>
        $(function () {
            $("#date1").datepicker({
                dateFormat: "yy/mm/dd",
                showButtonPanel: true,
                changeMonth: true,
                changeYear: true,
                gotoCurrent: true,
                onSelect: function (date) {
                    var d1 = $('#date1').datepicker('getDate');
                    var myDate = $.datepicker.formatDate('yy/mm/dd', d1);

                    // get date here
                    window.location.href = '@Url.Action("Index", "Retrieval")' + '?DueDate=' + myDate;
                }
            });
        });
    </script>
}

<h2>RETRIEVAL</h2>

<input id="date1" name="DueDate" class="form-control" value="@ViewBag.myDate" />

<table class="table table-striped table-hover">
    <tr>
        <th class="text-center text-info">
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th class="text-center text-info">
            @Html.DisplayNameFor(model => model.location)
        </th>
        <th class="text-center text-info">
            @Html.DisplayNameFor(model => model.balance)
        </th>
        <th class="text-center text-info">
            @Html.DisplayNameFor(model => model.quantityTotalNeed)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td align="center">
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td align="center">
                @Html.DisplayFor(modelItem => item.location)
            </td>
            <td align="center">
                @Html.DisplayFor(modelItem => item.balance)
            </td>
            <td align="center">
                @Html.DisplayFor(modelItem => item.quantityTotalNeed)
            </td>
            <td align="center">
                @Html.ActionLink("Edit", "Edit", new { itemNo = item.itemNo, DueDate = item.DueDate })
            </td>
        </tr>
    }
</table>
